services:
  bot:
    build: .
    command: python main.py
    environment:
      TELEGRAM_TOKEN:
      TELEGRAM_MAIN_CHAT_ID:
    restart: unless-stopped
    volumes:
      - db:/usr/src/app

volumes:
  db: