services:
  bot:
    build: .
    command: python main.py
    environment:
      TELEGRAM_TOKEN:
      TELEGRAM_MAIN_CHAT_ID:
    restart: unless-stopped
    volumes:
      - users_db:/usr/src/app/users.db

volumes:
  users_db: